export const CHANGE_THEME = 'CHANGE_THEME';
export const CACHE_BOOK = 'CACHE_BOOK';
export const ADD_BOOK = 'ADD_BOOK';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
